"""READING TABLE: Add height. Remove id

Revision ID: cdefc22c9aa9
Revises: d41e78b08d5f
Create Date: 2018-06-10 14:45:45.360499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdefc22c9aa9'
down_revision = 'd41e78b08d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'height')
    # ### end Alembic commands ###
